=== s5-dev/json-schemas/schema/media-metadata.json
{
    "$id": "https://schema.sfive.net/media-metadata.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Very flexible metadata format used for almost any more advanced content/media structure. Can be used for videos, images, music, podcasts, profiles, lists and more!",
    "type": "object",
    "properties": {
        "$schema": {
            "const": "https://schema.sfive.net/media-metadata.json"
        },
        "type": {
            "const": "media"
        },
        "name": {
            "type": "string",
            "maxLength": 255,
            "description": "Name of this Media object"
        },
        "details": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer",
                    "description": "Duration of this media object in milliseconds (can contain video or audio duration, but also more abstract durations like estimated read time)",
                    "minimum": 0
                }
            },
            "additionalProperties": false
        },
        "parents": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "cid": {
                        "$ref": "https://schema.sfive.net/cid.json"
                    },
                    "type": {
                        "type": "integer"
                    }
                },
                "additionalProperties": false
            },
            "maxItems": 255
        },
        "mediaTypes": {
            "type": "object",
            "propertyNames": {
                "type": "string",
                "enum": [
                    "application",
                    "audio",
                    "font",
                    "example",
                    "image",
                    "message",
                    "model",
                    "multipart",
                    "text",
                    "video"
                ]
            },
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "subtype": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "role": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "ext": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "cid": {
                            "$ref": "https://schema.sfive.net/cid.json"
                        },
                        "height": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "width": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "languages": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "maxLength": 16
                            },
                            "maxItems": 255
                        },
                        "asr": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "fps": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "bitrate": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "audioChannels": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "vcodec": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "acodec": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "container": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "dynamicRange": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "charset": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "value": {
                            "type": "string",
                            "maxLength": 65536
                        },
                        "duration": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "rows": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "columns": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "index": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "initRange": {
                            "type": "string",
                            "maxLength": 255
                        },
                        "indexRange": {
                            "type": "string",
                            "maxLength": 255
                        }
                    },
                    "required": [
                        "subtype"
                    ],
                    "additionalProperties": false
                },
                "maxItems": 255
            }
        },
        "links": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "minimum": 0
                },
                "head": {
                    "type": "array",
                    "items": {
                        "$ref": "https://schema.sfive.net/cid.json"
                    },
                    "maxItems": 255
                }
            },
            "additionalProperties": false
        },
        "extraMetadata": {
            "$ref": "https://schema.sfive.net/extra-metadata.json"
        }
    },
    "required": [
        "type",
        "name",
        "mediaTypes"
    ],
    "additionalProperties": false
}

=== s5-dev/json-schemas/example/media-metadata.json
{
    "$schema": "https://schema.sfive.net/media-metadata.json",
    "type": "media",
    "name": "Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film",
    "details": {
        "duration": 635000
    },
    "parents": [
        {
            "cid": "z3iFGXJzaHTVYgzh1QdkD5eN7nV1RxjxrpzMQJu2xexszroV",
            "type": 1
        }
    ],
    "mediaTypes": {
        "audio": [
            {
                "cid": "uJh8YJWrqf-ORJDA-0a9IT9_g387f7bnGLf9r2KdWbZIqb3RGJQ",
                "subtype": "mp4",
                "ext": "m4a",
                "asr": 22050,
                "bitrate": 30791,
                "audioChannels": 2,
                "acodec": "mp4a.40.5",
                "container": "m4a_dash",
                "initRange": "0-640",
                "indexRange": "641-1440"
            },
            {
                "cid": "uJh9PPTmRMugEZ5xl8VG-vvkihgEAmtACw1SZbX2QmpwStEP1KA",
                "subtype": "webm",
                "ext": "webm",
                "asr": 48000,
                "bitrate": 33838,
                "audioChannels": 2,
                "acodec": "opus",
                "container": "webm_dash",
                "initRange": "0-258",
                "indexRange": "259-1342"
            },
            {
                "cid": "uJh9crhzzHnmjqmYu8BIn2qLL9KWUuQMWXUyAkEzH23BlEdIQOw",
                "subtype": "mp4",
                "ext": "m4a",
                "asr": 22050,
                "bitrate": 48791,
                "audioChannels": 2,
                "acodec": "mp4a.40.5",
                "container": "m4a_dash",
                "initRange": "0-640",
                "indexRange": "641-1440"
            },
            {
                "cid": "uJh-9_83k8I5XmvqO5584TAkHkjaDmws3Lo62GaSneR6Kv6z8Ow",
                "subtype": "webm",
                "ext": "webm",
                "asr": 48000,
                "bitrate": 49559,
                "audioChannels": 2,
                "acodec": "opus",
                "container": "webm_dash",
                "initRange": "0-258",
                "indexRange": "259-1342"
            },
            {
                "cid": "uJh-59I1laF5ROhp-ebfUogK9mBbk5rkYWtn4_mZTDItTIvshTw",
                "subtype": "webm",
                "ext": "webm",
                "asr": 48000,
                "bitrate": 65377,
                "audioChannels": 2,
                "acodec": "opus",
                "container": "webm_dash",
                "initRange": "0-258",
                "indexRange": "259-1343"
            },
            {
                "cid": "uJh9V1IamR4YeUTvcur4GMdqgp0X_EdoRkuNvS1HnTJINg2Ex7A",
                "subtype": "mp4",
                "ext": "m4a",
                "asr": 24000,
                "bitrate": 195102,
                "audioChannels": 6,
                "acodec": "mp4a.40.5",
                "container": "m4a_dash",
                "initRange": "0-640",
                "indexRange": "641-1440"
            },
            {
                "cid": "uJh-v65xPYcO5bWv9jfWcXvAb9I62OiXBS3V82bxsvQ3aPa26nA",
                "subtype": "mp4",
                "ext": "m4a",
                "asr": 44100,
                "bitrate": 129480,
                "audioChannels": 2,
                "acodec": "mp4a.40.2",
                "container": "m4a_dash",
                "initRange": "0-631",
                "indexRange": "632-1431"
            },
            {
                "cid": "uJh-OfKVbFSfHB5oEZRLiGqbN4tiN_FwiGIpSGgRbkx_TDGKsmw",
                "subtype": "webm",
                "ext": "webm",
                "asr": 48000,
                "bitrate": 128612,
                "audioChannels": 2,
                "acodec": "opus",
                "container": "webm_dash",
                "initRange": "0-258",
                "indexRange": "259-1343"
            },
            {
                "cid": "uJh8dsx8v_vaALip2Rg4gHd8XMKUwpth58idxwITa58yN62720AE",
                "subtype": "mp4",
                "ext": "m4a",
                "asr": 48000,
                "bitrate": 384104,
                "audioChannels": 6,
                "acodec": "ac-3",
                "container": "m4a_dash",
                "initRange": "0-589",
                "indexRange": "590-1389"
            },
            {
                "cid": "uJh_UZtNM-x79KHE-sBZ-9JQ7VNAAM-pFzTpzw6SRPU1SLXD20AE",
                "subtype": "mp4",
                "ext": "m4a",
                "asr": 48000,
                "bitrate": 384104,
                "audioChannels": 6,
                "acodec": "ec-3",
                "container": "m4a_dash",
                "initRange": "0-591",
                "indexRange": "592-1391"
            },
            {
                "cid": "uJh8okIzMziikgDT8T6VbkLNgggj7bchRuxYqPH4SgatFO6B51QE",
                "subtype": "mp4",
                "ext": "m4a",
                "asr": 48000,
                "bitrate": 387851,
                "audioChannels": 6,
                "acodec": "mp4a.40.2",
                "container": "m4a_dash",
                "initRange": "0-631",
                "indexRange": "632-1431"
            }
        ],
        "image": [
            {
                "cid": "uJh8PC7iEZVKgxjOBgEc1bqPSfrBpvaaOG6DWWA7eQGSLzyOnAQ",
                "subtype": "jpeg",
                "role": "thumbnail",
                "ext": "jpg",
                "height": 720,
                "width": 1278
            },
            {
                "cid": "uJh_NIGyc9tgHhibp9IYTmGfOgTv0QTpHzSxBqO34HVZoCB4RAg",
                "subtype": "webp",
                "role": "thumbnail",
                "ext": "webp",
                "height": 720,
                "width": 1278
            },
            {
                "cid": "uJh-DrZLmIySXVVcHS9EgomhKGGp442qKybl2tFuMUDawf4pC",
                "subtype": "jpeg",
                "role": "thumbnail",
                "ext": "jpg",
                "height": 180,
                "width": 320
            },
            {
                "cid": "uJh_ah6MYNXMErEN2hltvnLwxnRRNCvlLL9nKg_IiGVciYJxC",
                "subtype": "webp",
                "role": "thumbnail",
                "ext": "webp",
                "height": 180,
                "width": 320
            },
            {
                "cid": "uJh9QkQMFBWpLL8zp65Ll47zOQRrawbVpKpFRSUk8Sa72RHqt",
                "subtype": "webp",
                "role": "storyboard",
                "ext": "webp",
                "height": 90,
                "width": 160,
                "duration": 124023,
                "rows": 5,
                "columns": 5,
                "index": 0
            },
            {
                "cid": "uJh9VlVxZhPkooAik8LPXud5dMze_3u0T4GiqmThYiFHlYerH",
                "subtype": "webp",
                "role": "storyboard",
                "ext": "webp",
                "height": 90,
                "width": 160,
                "duration": 124023,
                "rows": 5,
                "columns": 5,
                "index": 1
            },
            {
                "cid": "uJh8u-7l1UuDvIRVBgmG54jpFG99NeBwr7M8GbwXg3Hc2WbLi",
                "subtype": "webp",
                "role": "storyboard",
                "ext": "webp",
                "height": 90,
                "width": 160,
                "duration": 124023,
                "rows": 5,
                "columns": 5,
                "index": 2
            },
            {
                "cid": "uJh9OIJtuRX4c_SXI75SypyggciwvRWJObDAUaZyOPoAoAWLd",
                "subtype": "webp",
                "role": "storyboard",
                "ext": "webp",
                "height": 90,
                "width": 160,
                "duration": 124023,
                "rows": 5,
                "columns": 5,
                "index": 3
            },
            {
                "cid": "uJh-x1FH5V0vz1p_aknV05vJ8_vMbMqMMtmjjaQ3447G970yz",
                "subtype": "webp",
                "role": "storyboard",
                "ext": "webp",
                "height": 90,
                "width": 160,
                "duration": 124023,
                "rows": 5,
                "columns": 5,
                "index": 4
            },
            {
                "cid": "uJh9Vp4rPlZk9xXhNbBN-Qtv7UIPKWUvHcEo9lgSkyOlOT-wG",
                "subtype": "webp",
                "role": "storyboard",
                "ext": "webp",
                "height": 90,
                "width": 160,
                "duration": 14883,
                "rows": 5,
                "columns": 5,
                "index": 5
            }
        ],
        "text": [
            {
                "subtype": "plain",
                "role": "title",
                "ext": "yt-title.txt",
                "value": "Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film"
            },
            {
                "cid": "uJh_IFrQNjmo4tzPr-L2sMEvfKDMDLJAJ4D1qvHVDw1gNXbsB",
                "subtype": "plain",
                "role": "description",
                "ext": "yt-description.txt"
            },
            {
                "subtype": "plain",
                "role": "summary",
                "ext": "txt",
                "value": "Enjoy this UHD High Frame rate version of one of the iconic short films produced by Blender Institute!\nLearn more about the project here http://bbb3d.renderfarmâ€¦"
            }
        ],
        "video": [
            {
                "cid": "uJh8JM5X3WxHEqkQ1HyD36mEM1_b4ytTqU2HZ5WneyLXK790IJw",
                "subtype": "mp4",
                "ext": "mp4",
                "height": 144,
                "width": 256,
                "fps": 15,
                "bitrate": 32252,
                "vcodec": "avc1.4d400b",
                "container": "mp4_dash",
                "dynamicRange": "SDR",
                "initRange": "0-738",
                "indexRange": "739-2330"
            },
            {
                "cid": "uJh-MAY6S8KzIAtlkeylRfeF4nbxNbjtDrVrfY3ULtx7fRv3eHQ",
