=== s5-dev/json-schemas/schema/web-app-metadata.json
{
    "$id": "https://schema.sfive.net/web-app-metadata.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Metadata format used for web apps stored on S5",
    "type": "object",
    "properties": {
        "$schema": {
            "const": "https://schema.sfive.net/web-app-metadata.json"
        },
        "type": {
            "const": "web_app"
        },
        "name": {
            "type": "string",
            "maxLength": 255,
            "description": "Name of this Web App"
        },
        "tryFiles": {
            "type": "array",
            "items": {
                "type": "string",
                "maxLength": 255
            },
            "description": "If a requested path isn't found in the paths map directly, the web server will iterate through the requested path combined with every path in this list."
        },
        "errorPages": {
            "type": "object",
            "propertyNames": {
                "pattern": "^\\d{3}$"
            },
            "additionalProperties": {
                "type": "string",
                "maxLength": 255
            },
            "maxProperties": 32,
            "description": "If a requested path isn't found in the paths map or using tryFiles, the path referenced by the key \"404\" is loaded."
        },
        "paths": {
            "type": "object",
            "propertyNames": {
                "maxLength": 255
            },
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "cid": {
                        "$ref": "https://schema.sfive.net/cid.json"
                    },
                    "contentType": {
                        "type": "string",
                        "pattern": "^(application|audio|font|example|image|message|model|multipart|text|video)\\/[\\w+-.]{1,127}$"
                    }
                },
                "required": [
                    "cid"
                ],
                "additionalProperties": false
            },
            "maxProperties": 65536,
            "description": "Maps paths to CIDs. If a path is requested, this map is used to look it up."
        },
        "extraMetadata": {
            "$ref": "https://schema.sfive.net/extra-metadata.json"
        }
    },
    "required": [
        "type",
        "paths"
    ],
    "additionalProperties": false
}

=== s5-dev/json-schemas/example/web-app-metadata.json
{
    "$schema": "https://schema.sfive.net/web-app-metadata.json",
    "type": "web_app",
    "name": "JSON schemas",
    "tryFiles": [
        "index.html"
    ],
    "errorPages": {
        "404": "/404.html"
    },
    "extraMetadata": {},
    "paths": {
        "cid.json": {
            "cid": "uJh9jAcNhEciIXEpZaUC5ScbnaRo7m69urYDL0Jzr7bSjTR0B",
            "contentType": "application/json"
        },
        "media-metadata.json": {
            "cid": "uJh-TcT3syDJKUCp2Y3QexX1qk_7xrCRdGjOGxgheLz_Ry8sa",
            "contentType": "application/json"
        },
        "extra-metadata.json": {
            "cid": "uJh_UiQG5oqOnwzwdsx9L9NYQPLodLE9ZIEK6cQ1MxdUgbR8J",
            "contentType": "application/json"
        },
        "web-app-metadata.json": {
            "cid": "uJh-77lY4QMKN6iwPt39ifJ7GUMPLeTd5U-zCv0ttArmV-HkJ",
            "contentType": "application/json"
        }
    }
}
